USE kyc_db;

SET FOREIGN_KEY_CHECKS = 0;

LOAD DATA LOCAL INFILE 'client.csv' 
INTO TABLE client 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'client_address.csv' 
INTO TABLE client_address 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'onboarding_case.csv' 
INTO TABLE onboarding_case 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'document.csv' 
INTO TABLE document 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

LOAD DATA LOCAL INFILE 'risk_classification.csv' 
INTO TABLE risk_classification 
FIELDS TERMINATED BY ',' ENCLOSED BY '"' 
LINES TERMINATED BY '\n' 
IGNORE 1 ROWS;

SET FOREIGN_KEY_CHECKS = 1;